FROM oven/bun:1.2.20-alpine

WORKDIR /app

COPY package.json bun.lock turbo.json tsconfig.json ./
COPY apps ./apps
COPY packages ./packages
COPY seed*.ts ./
COPY reset.ts ./

RUN bun install --frozen-lockfile

ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000

CMD ["bun", "run", "start:server:with-migrations"]
